name: cfn-security Scan

on: [push]

jobs:
  ## all scans
  security-scan-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@master
      with:
        cloudformation_directory: "./cloudformation/"
        scanner: "all"
