name: cfn-security Scan

on: [push]

jobs:
  ## cfn-nag, cfn-guard, and checkov security scan
  security-scan-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@all-tools
      with:
        cloudformation_directory: "./cloudformation/"
        scanner: "all"