name: cfn-guard Security Scan

on: [push]

jobs:
  ## cfn-guard security scan
  security-scan-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@all-tools
      with:
        cloudformation_directory: './cloudformation/' ## change to your template directory
        scanner: "cfn-guard"