name: Checkov Security Scan

on: [push]

jobs:
  security-scan-checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: grolston/cfn-security@master
      env:
        CLOUDFORMATION_DIRECTORY: "./cloudformation/"
        TEST: "checkov"