name: 'cfn-security'
description: 'CloudFormation Static Code Analysis Tool Suite'
author: grolston
inputs:
  cloudformation_directory:
    description: 'directory within git repo to scan cloudformation templates'
    required: true
  scanner:
    description: 'scanner used to run security test. Options are "cfn-nag", "cfn-guard", "checkov", "all"'
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield
  color: green
